travis:
  secure:
    BINSTAR_TOKEN: XP+w+/V3vhaUPy7QThpoEth5uex1DL19IQYnRcnOz6VJ6UrzcrqyMuNJeiw6v/VANjzgnbglkSNEiuPtJX1MXnGLbdB6lLYT7dZ1qFv1Hj6TmuJPwlOngaHF/KbHxHCOwiYoZTHoiKUY8kUtfXFO+h9ghz8LKiGDBnD3kpPny2XrBAbmLOGlfqf0zt2iSgJQlXJdSRfy+JJRnoObkHmn/yAfrGBefec7XlWj86EQb2ADJgp/eN34cjKeq28ZEJN7eAzVqBaLG3f8TolfjS7a56di9M/7ZS6/zpWMeS0FleVbY6tXHYC0/f3n0a6G5wgwYWNmhsJZOTrYQM81q9c4dvqA2mTHfa9o2MwIGxNPeXQtTktdzRBgPqPjQQI/qgQ/febdsBKGoCYZw0/1ti53ka0nChmHMOmxZ2w/cWkcoXqfiVZqyL1uLSENhC6ci+viwvpw9NWDVELuy3EZbBl4jLMN7EZYezAa9Agdu6tuM9xjTBkoGBJrdE7A8/r1p2HW9OqMdkT81Ir9C3YQnq1ZNx1XViTx6KD1tvunQaNocsPBnOcLpnq+I0JxOddFheUcrh96y9ipGl26cRX/sXr1YFX2tURmOIlHoBa72TCyU4aHHjqRDOCCXf8tA45Vr4uWj+QV6YoIA07p4TmSovtys+NV2eQtDzt2UCIjTO0wfPo=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
